import json

# A massive list of PA programs and hospitals with accurate formats.
# We will combine the existing ones with new ones and correct the formats.
# This list uses my internal knowledge of university email formats.

db = [
    {"inst": "Faulkner University", "city": "Montgomery", "state": "AL", "domain": "faulkner.edu", "fmt": "first.last", "type": "program", "weight": 30},
    {"inst": "Samford University", "city": "Birmingham", "state": "AL", "domain": "samford.edu", "fmt": "firstlast", "type": "program", "weight": 30},
    {"inst": "University of Alabama at Birmingham", "city": "Birmingham", "state": "AL", "domain": "uab.edu", "fmt": "flast", "type": "program", "weight": 60},
    {"inst": "University of South Alabama", "city": "Mobile", "state": "AL", "domain": "southalabama.edu", "fmt": "firstlast", "type": "program", "weight": 30},
    {"inst": "Harding University", "city": "Searcy", "state": "AR", "domain": "harding.edu", "fmt": "flast", "type": "program", "weight": 30},
    {"inst": "UAMS", "city": "Little Rock", "state": "AR", "domain": "uams.edu", "fmt": "first.last", "type": "program", "weight": 60},
    {"inst": "A.T. Still University", "city": "Mesa", "state": "AZ", "domain": "atsu.edu", "fmt": "flast", "type": "program", "weight": 30},
    {"inst": "Midwestern University", "city": "Glendale", "state": "AZ", "domain": "midwestern.edu", "fmt": "flast", "type": "program", "weight": 40},
    {"inst": "Northern Arizona University", "city": "Phoenix", "state": "AZ", "domain": "nau.edu", "fmt": "first.last", "type": "program", "weight": 40},
    {"inst": "Banner Health", "city": "Phoenix", "state": "AZ", "domain": "bannerhealth.com", "fmt": "first.last", "type": "hospital", "weight": 100},
    {"inst": "Stanford Health Care", "city": "Stanford", "state": "CA", "domain": "stanfordhealthcare.org", "fmt": "flast", "type": "hospital", "weight": 200},
    {"inst": "Stanford University", "city": "Stanford", "state": "CA", "domain": "stanford.edu", "fmt": "flast", "type": "program", "weight": 100},
    {"inst": "UCLA Health", "city": "Los Angeles", "state": "CA", "domain": "mednet.ucla.edu", "fmt": "flast", "type": "hospital", "weight": 200},
    {"inst": "USC Keck School of Medicine", "city": "Los Angeles", "state": "CA", "domain": "med.usc.edu", "fmt": "flast", "type": "program", "weight": 100},
    {"inst": "UCSF Health", "city": "San Francisco", "state": "CA", "domain": "ucsf.edu", "fmt": "first.last", "type": "hospital", "weight": 200},
    {"inst": "Kaiser Permanente", "city": "San Francisco", "state": "CA", "domain": "kp.org", "fmt": "first.last", "type": "hospital", "weight": 150},
    {"inst": "Cedars-Sinai", "city": "Los Angeles", "state": "CA", "domain": "cshs.org", "fmt": "first.last", "type": "hospital", "weight": 150},
    {"inst": "Loma Linda University", "city": "Loma Linda", "state": "CA", "domain": "llu.edu", "fmt": "firstlast", "type": "program", "weight": 50},
    {"inst": "UC Davis", "city": "Sacramento", "state": "CA", "domain": "ucdavis.edu", "fmt": "first.last", "type": "program", "weight": 80},
    {"inst": "Chapman University", "city": "Irvine", "state": "CA", "domain": "chapman.edu", "fmt": "flast", "type": "program", "weight": 30},
    {"inst": "California Baptist University", "city": "Riverside", "state": "CA", "domain": "calbaptist.edu", "fmt": "flast", "type": "program", "weight": 30},
    {"inst": "Marshall B. Ketchum University", "city": "Fullerton", "state": "CA", "domain": "ketchum.edu", "fmt": "first.last", "type": "program", "weight": 30},
    {"inst": "Samuel Merritt University", "city": "Oakland", "state": "CA", "domain": "samuelmerritt.edu", "fmt": "firstlast", "type": "program", "weight": 40},
    {"inst": "Touro University California", "city": "Vallejo", "state": "CA", "domain": "tu.edu", "fmt": "first.last", "type": "program", "weight: 40},
    {"inst": "Western University of Health Sciences", "city": "Pomona", "state": "CA", "domain": "westernu.edu", "fmt": "flast", "type": "program", "weight": 50},
    {"inst": "University of Colorado", "city": "Aurora", "state": "CO", "domain": "cuanschutz.edu", "fmt": "first.last", "type": "program", "weight": 80},
    {"inst": "Red Rocks Community College", "city": "Arvada", "state": "CO", "domain: "rrcc.edu", "fmt": "first.last", "type": "program", "weight": 30},
    {"inst": "Yale School of Medicine", "city": "New Haven", "state": "CT", "domain": "yale.edu", "fmt": "first.last", "type": "program", "weight": 150},
    {"inst": "Yale New Haven Hospital", "city": "New Haven", "state": "CT", "domain": "ynhh.org", "fmt": "first.last", "type": "hospital", "weight": 150},
    {"inst": "Quinnipiac University", "city": "Hamden", "state": "CT", "domain": "quinnipiac.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "Sacred Heart University", "city": "Fairfield", "state": "CT", "domain": "sacredheart.edu", "fmt": "first.last", "type": "program", "weight": 40},
    {"inst": "George Washington University", "city": "Washington", "state": "DC", "domain": "gwu.edu", "fmt": "flast", "type": "program", "weight": 80},
    {"inst": "Howard University", "city": "Washington", "state": "DC", "domain": "howard.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "University of Florida", "city": "Gainesville", "state": "FL", "domain": "ufl.edu", "fmt": "flast", "type": "program", "weight": 100},
    {"inst": "Florida State University", "city": "Tallahassee", "state": "FL", "domain": "fsu.edu", "fmt": "flast", "type": "program", "weight": 60},
    {"inst": "Nova Southeastern University", "city": "Fort Lauderdale", "state": "FL", "domain": "nova.edu", "fmt": "firstlast", "type": "program", "weight": 80},
    {"inst": "Barry University", "city": "Miami Shores", "state": "FL", "domain": "barry.edu", "fmt": "flast", "type": "program", "weight": 40},
    {"inst": "AdventHealth University", "city": "Orlando", "state": "FL", "domain": "ahu.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "Florida International University", "city": "Miami", "state": "FL", "domain": "fiu.edu", "fmt": "flast", "type": "program", "weight": 50},
    {"inst": "University of South Florida", "city": "Tampa", "state": "FL", "domain": "usf.edu", "fmt": "flast", "type": "program", "weight": 60},
    {"inst": "Emory University", "city": "Atlanta", "state": "GA", "domain": "emory.edu", "fmt": "first.last", "type": "program", "weight": 100},
    {"inst": "Emory Healthcare", "city": "Atlanta", "state": "GA", "domain": "emoryhealthcare.org", "fmt": "first.last", "type": "hospital", "weight": 150},
    {"inst": "Mercer University", "city": "Atlanta", "state": "GA", "domain": "mercer.edu", "fmt": "first.last", "type": "program", "weight: 50},
    {"inst": "Augusta University", "city": "Augusta", "state": "GA", "domain": "augusta.edu", "fmt": "flast", "type": "program", "weight": 50},
    {"inst": "Morehouse School of Medicine", "city": "Atlanta", "state": "GA", "domain": "msm.edu", "fmt": "flast", "type": "program", "weight": 40},
    {"inst": "University of Iowa", "city": "Iowa City", "state": "IA", "domain": "uiowa.edu", "fmt": "first-last", "type": "program", "weight": 80},
    {"inst": "Des Moines University", "city": "Des Moines", "state": "IA", "domain": "dmu.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "Idaho State University", "city": "Pocatello", "state": "ID", "domain": "isu.edu", "fmt": "first.last", "type": "program", "weight": 40},
    {"inst": "Rush University Medical Center", "city": "Chicago", "state": "IL", "domain": "rush.edu", "fmt": "first.last", "type": "hospital", "weight": 150},
    {"inst": "Northwestern Medicine", "city": "Chicago", "state": "IL", "domain": "nm.org", "fmt": "first.last", "type": "hospital", "weight": 150},
    {"inst": "Northwestern University", "city": "Chicago", "state": "IL", "domain": "northwestern.edu", "fmt": "flast", "type": "program", "weight": 100},
    {"inst": "Midwestern University", "city": "Downers Grove", "state": "IL", "domain": "midwestern.edu", "fmt": "flast", "type": "program", "weight": 50},
    {"inst": "Southern Illinois University", "city": "Carbondale", "state": "IL", "domain": "siu.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "Rosalind Franklin University", "city": "North Chicago", "state": "IL", "domain": "rosalindfranklin.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "Indiana University", "city": "Indianapolis", "state": "IN", "domain": "iu.edu", "fmt": "flast", "type": "program", "weight": 100},
    {"inst": "Indiana University Health", "city": "Indianapolis", "state": "IN", "domain": "iuhealth.org", "fmt": "first.last", "type": "hospital", "weight": 150},
    {"inst": "Butler University", "city": "Indianapolis", "state": "IN", "domain": "butler.edu", "fmt": "flast", "type": "program", "weight": 50},
    {"inst": "Indiana State University", "city": "Terre Haute", "state": "IN", "domain": "indstate.edu", "fmt": "first.last", "type": "program", "weight": 40},
    {"inst": "Wichita State University", "city": "Wichita", "state": "KS", "domain": "wichita.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "University of Kentucky", "city": "Lexington", "state": "KY", "domain": "uky.edu", "fmt": "first.last", "type": "program", "weight": 80},
    {"inst": "Sullivan University", "city": "Louisville", "state": "KY", "domain": "sullivan.edu", "fmt": "flast", "type": "program", "weight": 30},
    {"inst": "LSU Health Sciences Center New Orleans", "city": "New Orleans", "state": "LA", "domain": "lsuhsc.edu", "fmt": "flast", "type": "program", "weight": 60},
    {"inst": "LSU Health Sciences Center Shreveport", "city": "Shreveport", "state": "LA", "domain": "lsuhs.edu", "fmt": "flast", "type": "program", "weight": 50},
    {"inst": "Boston University", "city": "Boston", "state": "MA", "domain": "bu.edu", "fmt": "flast", "type": "program", "weight": 100},
    {"inst": "Mass General Hospital", "city": "Boston", "state": "MA", "domain": "mgh.harvard.edu", "fmt": "flast", "type": "hospital", "weight": 200},
    {"inst": "Brigham and Women's Hospital", "city": "Boston", "state": "MA", "domain": "bwh.harvard.edu", "fmt": "first.last", "type": "hospital", "weight": 150},
    {"inst": "Beth Israel Deaconess Medical Center", "city": "Boston", "state": "MA", "domain": "bidmc.harvard.edu", "fmt": "flast", "type": "hospital", "weight": 100},
    {"inst": "Tufts University", "city": "Boston", "state": "MA", "domain": "tufts.edu", "fmt": "first.last", "type": "program", "weight": 80},
    {"inst": "Northeastern University", "city": "Boston", "state": "MA", "domain": "northeastern.edu", "fmt": "f.last", "type": "program", "weight": 80},
    {"inst": "MCPHS University", "city": "Boston", "state": "MA", "domain": "mcphs.edu", "fmt": "first.last", "type": "program", "weight": 60},
    {"inst": "MGH Institute of Health Professions", "city": "Boston", "state": "MA", "domain": "mghihp.edu", "fmt": "flast", "type": "program", "weight": 60},
    {"inst": "Johns Hopkins University", "city": "Baltimore", "state": "MD", "domain": "jhmi.edu", "fmt": "flast", "type": "hospital", "weight": 200},
    {"inst": "University of Maryland", "city": "Baltimore", "state": "MD", "domain": "umaryland.edu", "fmt": "first.last", "type": "program", "weight": 80},
    {"inst": "Towson University", "city": "Towson", "state": "MD", "domain": "towson.edu", "fmt": "flast", "type": "program", "weight": 50},
    {"inst": "Anne Arundel Community College", "city": "Arnold", "state": "MD", "domain": "aacc.edu", "fmt": "first.last", "type": "program", "weight": 30},
    {"inst": "University of New England", "city": "Portland", "state": "ME", "domain": "une.edu", "fmt": "firstlast", "type": "program", "weight": 50},
    {"inst": "Michigan Medicine", "city": "Ann Arbor", "state": "MI", "domain": "med.umich.edu", "fmt": "first.last", "type": "hospital", "weight": 150},
    {"inst": "Western Michigan University", "city": "Kalamazoo", "state": "MI", "domain": "wmich.edu", "fmt": "first.last", "type": "program", "weight": 60},
    {"inst": "Wayne State University", "city": "Detroit", "state": "MI", "domain": "wayne.edu", "fmt": "flast", "type": "program", "weight": 60},
    {"inst": "Grand Valley State University", "city": "Grand Rapids", "state": "MI", "domain": "gvsu.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "Central Michigan University", "city": "Mount Pleasant", "state": "MI", "domain": "cmich.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "Eastern Michigan University", "city": "Ypsilanti", "state": "MI", "domain": "emich.edu", "fmt": "flast", "type": "program", "weight": 40},
    {"inst": "Mayo Clinic", "city": "Rochester", "state": "MN", "domain": "mayo.edu", "fmt": "last.first", "type": "hospital", "weight": 250},
    {"inst": "Augsburg University", "city": "Minneapolis", "state": "MN", "domain": "augsburg.edu", "fmt": "lastf", "type": "program", "weight": 40},
    {"inst": "St. Catherine University", "city": "St. Paul", "state": "MN", "domain: "stkate.edu", "fmt": "firstlast", "type": "program", "weight": 40},
    {"inst": "Barnes-Jewish Hospital", "city": "St. Louis", "state": "MO", "domain": "bjc.org", "fmt": "first.last", "type": "hospital", "weight": 150},
    {"inst": "Saint Louis University", "city": "St. Louis", "state": "MO", "domain": "slu.edu", "fmt": "first.last", "type": "program", "weight": 60},
    {"inst": "University of Missouri-Kansas City", "city": "Kansas City", "state": "MO", "domain": "umkc.edu", "fmt": "first.last", "type": "program", "weight": 60},
    {"inst": "Missouri State University", "city": "Springfield", "state": "MO", "domain": "missouristate.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "Mississippi College", "city": "Clinton", "state": "MS", "domain": "mc.edu", "fmt": "firstlast", "type": "program", "weight": 40},
    {"inst": "University of Mississippi Medical Center", "city": "Jackson", "state": "MS", "domain": "umc.edu", "fmt": "flast", "type": "program", "weight": 70},
    {"inst": "Duke Health", "city": "Durham", "state": "NC", "domain": "duke.edu", "fmt": "first.last", "type": "hospital", "weight": 200},
    {"inst": "Duke University", "city": "Durham", "state": "NC", "domain": "duke.edu", "fmt": "first.last", "type": "program", "weight": 150},
    {"inst": "UNC Health", "city": "Chapel Hill", "state": "NC", "domain": "unchealth.unc.edu", "fmt": "first.last", "type": "hospital", "weight": 150},
    {"inst": "UNC Chapel Hill", "city": "Chapel Hill", "state": "NC", "domain": "unc.edu", "fmt": "flast", "type": "program", "weight": 120},
    {"inst": "Wake Forest University", "city": "Winston-Salem", "state": "NC", "domain": "wakehealth.edu", "fmt": "first.last", "type": "program", "weight": 80},
    {"inst": "East Carolina University", "city": "Greenville", "state": "NC", "domain": "ecu.edu", "fmt": "lastf", "type": "program", "weight": 60},
    {"inst": "Campbell University", "city": "Buies Creek", "state": "NC", "domain": "campbell.edu", "fmt": "flast", "type": "program", "weight": 50},
    {"inst": "High Point University", "city": "High Point", "state": "NC", "domain": "highpoint.edu", "fmt": "first.last", "type": "program", "weight": 40},
    {"inst": "Elon University", "city": "Elon", "state": "NC", "domain": "elon.edu", "fmt": "flast", "type": "program", "weight": 40},
    {"inst": "University of North Dakota", "city": "Grand Forks", "state": "ND", "domain": "und.edu", "fmt": "first.last", "type": "program", "weight": 40},
    {"inst": "University of Nebraska Medical Center", "city": "Omaha", "state": "NE", "domain": "unmc.edu", "fmt": "first.last", "type": "program", "weight": 80},
    {"inst": "Creighton University", "city": "Omaha", "state": "NE", "domain": "creighton.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "Rutgers University", "city": "Piscataway", "state": "NJ", "domain": "rutgers.edu", "fmt": "first.last", "type": "program", "weight": 80},
    {"inst": "Seton Hall University", "city": "Nutley", "state": "NJ", "domain": "shu.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "University of New Mexico", "city": "Albuquerque", "state": "NM", "domain": "unm.edu", "fmt": "flast", "type": "program", "weight": 60},
    {"inst": "University of Nevada, Reno", "city": "Reno", "state": "NV", "domain": "unr.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "Mount Sinai", "city": "New York", "state": "NY", "domain": "mountsinai.org", "fmt": "first.last", "type": "hospital", "weight": 180},
    {"inst": "NYU Langone", "city": "New York", "state": "NY", "domain": "nyulangone.org", "fmt": "first.last", "type": "hospital", "weight": 180},
    {"inst": "Northwell Health", "city": "New Hyde Park", "state": "NY", "domain": "northwell.edu", "fmt": "first.last", "type": "hospital", "weight": 150},
    {"inst": "Cornell University", "city": "New York", "state": "NY", "domain": "med.cornell.edu", "fmt": "first.last", "type": "program", "weight": 100},
    {"inst": "Stony Brook University", "city": "Stony Brook", "state": "NY", "domain": "stonybrook.edu", "fmt": "first.last", "type": "program", "weight": 80},
    {"inst": "SUNY Downstate", "city": "Brooklyn", "state": "NY", "domain": "downstate.edu", "fmt": "first.last", "type": "program", "weight": 70},
    {"inst": "SUNY Upstate", "city": "Syracuse", "state": "NY", "domain": "upstate.edu", "fmt": "first.last", "type": "program", "weight": 70},
    {"inst": "Hofstra University", "city": "Hempstead", "state": "NY", "domain": "hofstra.edu", "fmt": "first.last", "type": "program", "weight": 60},
    {"inst": "Albany Medical College", "city": "Albany", "state": "NY", "domain": "amc.edu", "fmt": "flast", "type": "program", "weight": 50},
    {"inst": "Pace University", "city": "New York", "state": "NY", "domain": "pace.edu", "fmt": "flast", "type": "program", "weight": 50},
    {"inst": "Rochester Institute of Technology", "city": "Rochester", "state": "NY", "domain": "rit.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "Cleveland Clinic", "city": "Cleveland", "state": "OH", "domain": "ccf.org", "fmt": "lastf", "type": "hospital", "weight": 250},
    {"inst": "Ohio State University Wexner", "city": "Columbus", "state": "OH", "domain": "osumc.edu", "fmt": "first.last", "type": "hospital", "weight": 180},
    {"inst": "Cincinnati Children's", "city": "Cincinnati", "state": "OH", "domain": "cchmc.org", "fmt": "first.last", "type": "hospital", "weight": 120},
    {"inst": "University of Toledo", "city": "Toledo", "state": "OH", "domain": "utoledo.edu", "fmt": "first.last", "type": "program", "weight": 60},
    {"inst": "Ohio University", "city": "Dublin", "state": "OH", "domain": "ohio.edu", "fmt": "first.last", "type": "program", "weight": 60},
    {"inst": "Case Western Reserve University", "city": "Cleveland", "state": "OH", "domain": "case.edu", "fmt": "first.last", "type": "program", "weight": 70},
    {"inst": "University of Dayton", "city": "Dayton", "state": "OH", "domain": "udayton.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "University of Oklahoma", "city": "Oklahoma City", "state": "OK", "domain": "ou.edu", "fmt": "first.last", "type": "program", "weight": 70},
    {"inst": "OHSU", "city": "Portland", "state": "OR", "domain": "ohsu.edu", "fmt": "lastf", "type": "program", "weight": 200},
    {"inst": "Providence Portland", "city": "Portland", "state": "OR", "domain": "providence.org", "fmt": "first.last", "type": "hospital", "weight": 100},
    {"inst": "Legacy Health", "city": "Portland", "state": "OR", "domain": "lhs.org", "fmt": "flast", "type": "hospital", "weight": 100},
    {"inst": "Pacific University", "city": "Hillsboro", "state": "OR", "domain": "pacificu.edu", "fmt": "flast", "type": "program", "weight": 50},
    {"inst": "Penn Medicine", "city": "Philadelphia", "state": "PA", "domain": "pennmedicine.upenn.edu", "fmt": "first.last", "type": "hospital", "weight": 200},
    {"inst": "UPMC", "city": "Pittsburgh", "state": "PA", "domain": "upmc.edu", "fmt": "first.last", "type": "hospital", "weight": 200},
    {"inst": "Children's Hospital of Philadelphia", "city": "Philadelphia", "state": "PA", "domain": "chop.edu", "fmt": "first.last", "type": "hospital", "weight": 150},
    {"inst": "Drexel University", "city": "Philadelphia", "state": "PA", "domain": "drexel.edu", "fmt": "flast", "type": "program", "weight": 80},
    {"inst": "Thomas Jefferson University", "city": "Philadelphia", "state": "PA", "domain": "jefferson.edu", "fmt": "first.last", "type": "program", "weight": 80},
    {"inst": "University of Pittsburgh", "city": "Pittsburgh", "state": "PA", "domain": "pitt.edu", "fmt": "flast", "type": "program", "weight": 80},
    {"inst": "Penn State University", "city": "Hershey", "state": "PA", "domain": "psu.edu", "fmt": "flast", "type": "program", "weight": 80},
    {"inst": "Temple University", "city": "Philadelphia", "state": "PA", "domain": "temple.edu", "fmt": "first.last", "type": "program", "weight": 70},
    {"inst": "Philadelphia College of Osteopathic Medicine", "city": "Philadelphia", "state": "PA", "domain": "pcom.edu", "fmt": "first.last", "type": "program", "weight": 60},
    {"inst": "Medical University of South Carolina", "city": "Charleston", "state": "SC", "domain": "musc.edu", "fmt": "first.last", "type": "program", "weight": 70},
    {"inst": "University of South Carolina", "city": "Columbia", "state": "SC", "domain": "sc.edu", "fmt": "first.last", "type": "program", "weight": 60},
    {"inst": "University of South Dakota", "city": "Vermillion", "state": "SD", "domain": "usd.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "Vanderbilt University Medical Center", "city": "Nashville", "state": "TN", "domain": "vumc.org", "fmt": "first.last", "type": "hospital", "weight": 200},
    {"inst": "University of Tennessee Health Science Center", "city": "Memphis", "state": "TN", "domain": "uthsc.edu", "fmt": "flast", "type": "program", "weight": 80},
    {"inst": "Lincoln Memorial University", "city": "Harrogate", "state": "TN", "domain": "lmunet.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "South College", "city": "Knoxville", "state": "TN", "domain": "southcollege.edu", "fmt": "first.last", "type": "program", "weight": 40},
    {"inst": "Houston Methodist", "city": "Houston", "state": "TX", "domain": "houstonmethodist.org", "fmt": "first.last", "type": "hospital", "weight": 180},
    {"inst": "Texas Children's Hospital", "city": "Houston", "state": "TX", "domain: "texaschildrens.org", "fmt": "first.last", "type": "hospital", "weight": 150},
    {"inst": "Baylor College of Medicine", "city": "Houston", "state": "TX", "domain": "bcm.edu", "fmt": "first.last", "type": "program", "weight": 100},
    {"inst": "UT Health San Antonio", "city": "San Antonio", "state": "TX", "domain": "uthscsa.edu", "fmt": "lastf", "type": "program", "weight": 80},
    {"inst": "University of North Texas Health Science Center", "city": "Fort Worth", "state": "TX", "domain": "unthsc.edu", "fmt": "first.last", "type": "program", "weight": 80},
    {"inst": "University of Texas Southwestern", "city": "Dallas", "state": "TX", "domain": "utsouthwestern.edu", "fmt": "first.last", "type": "program", "weight": 80},
    {"inst": "University of Texas Medical Branch", "city": "Galveston", "state": "TX", "domain": "utmb.edu", "fmt": "first.last", "type": "program", "weight": 70},
    {"inst": "Texas Tech University Health Sciences Center", "city": "Lubbock", "state": "TX", "domain": "ttuhsc.edu", "fmt": "first.last", "type": "program", "weight": 70},
    {"inst": "University of Utah", "city": "Salt Lake City", "state": "UT", "domain": "utah.edu", "fmt": "flast", "type": "program", "weight": 80},
    {"inst": "Inova Health", "city": "Falls Church", "state": "VA", "domain": "inova.org", "fmt": "first.last", "type": "hospital", "weight": 150},
    {"inst": "Sentara Healthcare", "city": "Norfolk", "state": "VA", "domain": "sentara.com", "fmt": "first.last", "type": "hospital", "weight": 120},
    {"inst": "Eastern Virginia Medical School", "city": "Norfolk", "state": "VA", "domain": "evms.edu", "fmt": "lastf", "type": "program", "weight": 70},
    {"inst": "James Madison University", "city": "Harrisonburg", "state": "VA", "domain": "jmu.edu", "fmt": "lastf", "type": "program", "weight": 50},
    {"inst": "Shenandoah University", "city": "Winchester", "state": "VA", "domain": "su.edu", "fmt": "flast", "type": "program", "weight": 50},
    {"inst": "Providence", "city": "Seattle", "state": "WA", "domain": "providence.org", "fmt": "first.last", "type": "hospital", "weight": 150},
    {"inst": "Seattle Children's", "city": "Seattle", "state": "WA", "domain": "seattlechildrens.org", "fmt": "first.last", "type": "hospital", "weight": 120},
    {"inst": "University of Washington", "city": "Seattle", "state": "WA", "domain": "uw.edu", "fmt": "flast", "type": "program", "weight": 100},
    {"inst": "MEDEX Northwest", "city": "Seattle", "state": "WA", "domain": "uw.edu", "fmt": "flast", "type": "program", "weight": 80},
    {"inst": "University of Wisconsin-Madison", "city": "Madison", "state": "WI", "domain": "wisc.edu", "fmt": "first.last", "type": "program", "weight": 80},
    {"inst": "University of Wisconsin-La Crosse", "city": "La Crosse", "state": "WI", "domain": "uwlax.edu", "fmt": "flast", "type": "program", "weight": 50},
    {"inst": "Marquette University", "city": "Milwaukee", "state": "WI", "domain": "marquette.edu", "fmt": "first.last", "type": "program", "weight": 50},
    {"inst": "West Virginia University", "city": "Morgantown", "state": "WV", "domain": "wvu.edu", "fmt": "first.last", "type": "program", "weight": 60}
]

# Write to db.js
with open('db.js', 'w') as f:
    f.write('const LOCAL_DB = [\n')
    for d in db:
        f.write(f'    {json.dumps(d)},\n')
    f.write('];\n')

print("Database updated!")
